# Write a Python program that connects to a SQLite database named inventory.db. This database contains 
# two tables Products and Sales. Products table has attributes product_id, product_name, unit_price, and 
# quantity_on_hand. Sales table has attributes sale_id, product_id, quantity_sold, and sale_date.

# a) Retrieve the contents of the Products and Sales tables and display on the screen.
# b) Display product details for products that have been sold (product_id exists in Sales table).
# c) Validate product_id using regular expressions. If the product_id is not valid (e.g., not in the 
# correct format or does not exist in Products table), delete such records from Sales table and display.
# d) Compute the total revenue generated by each product (total sales amount) and display it in the dictionary 
# form (product_id, product_name, total_revenue).
# e) Dictionary item format should be: (product_id, product_name, total_revenue).

import sqlite3

conn = sqlite3.connect('inventory.db')
cursor = conn.cursor()

cursor.execute("insert into products values('PR0001', 'Mangoes', 100, 5000)")
cursor.execute("insert into products values('PR0002', 'Bananas', 600, 2000)")
cursor.execute("insert into products values('PR0003', 'Guavas', 70, 8000)")
cursor.execute("insert into products values('PR0004', 'Pears', 100, 2000)")
cursor.execute("insert into products values('PR0005', 'Apples', 200, 1000)")
cursor.execute("insert into products values('PR0006', 'Kiwis', 300, 500)")
cursor.execute("insert into products values('RP0006', 'Kiwis', 300, 500)")


cursor.execute("insert into sales values(31, 'PR0001', 200, '09-12-2024')")
cursor.execute("insert into sales values(32, 'PR0002', 450, '12-09-2024')")
cursor.execute("insert into sales values(33, 'PR0003', 320, '11-01-2024')")
cursor.execute("insert into sales values(34, 'PR0004', 215, '14-08-2024')")
cursor.execute("insert into sales values(35, 'PR0005', 800, '15-06-2024')")
cursor.execute("insert into sales values(36, 'PR0006', 270, '20-07-2024')")
cursor.execute("insert into sales values(37, 'RP0006', 270, '20-07-2024')")


conn.commit()
conn.close()